[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Content-Security-Policy = "default-src 'none'; script-src-elem 'self' https://cdnjs.cloudflare.com https://cloudfront.net *.cloudfront.net; script-src 'self' https://cdnjs.cloudflare.com https://cloudfront.net; connect-src 'self'; img-src 'self' https://gossipsweb.net/images/ https://cloudfront.net *.cloudfront.net; style-src-elem 'self' https://cloudfront.net *.cloudfront.net; style-src 'self' 'sha256-z8svcPpzK4DzYPsXNLt+Ycnf7ZWWMgaV1WgM+hCyt+g=' https://cloudfront.net *.cloudfront.net; base-uri 'self'; font-src 'self'; frame-src 'self'; form-action 'self';"
    # Permissions-Policy= "encrypted-media=(src); accelerometer=(); ambient-light-sensor=(); autoplay=(); camera=(); fullscreen=(self); geolocation=(); gyroscope=(); magnetometer=(); microphone=(); midi=(); payment=(self); picture-in-picture=(); speaker=(); sync-xhr=(); usb=(); vr=();"
    # Feature Policy is to be renamed to Permissions-Policy, however it is widely unsupported in majority of browsers.
    # Browser payment may be used.
    Feature-Policy = "accelerometer 'none'; autoplay 'none'; camera 'none'; encrypted-media 'self'; fullscreen 'self'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; payment 'self'; picture-in-picture 'none'; sync-xhr 'none'; usb 'none';"
    Set-Cookie = "SameSite=Strict; Secure"

[build.environment]
  NODE_VERSION = "14"
  NPM_FLAGS = "--prefix=/dev/null"

[build]
  base = "/"
  publish = "dist/"
  command = "pnpm i && pnpm run config && pnpm build || ( npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run config && npx pnpm build)"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

[[redirects]]
  from = "/home"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/index"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/alex"
  to = "/"
  status = 301
  force = true
