[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Content-Security-Policy = "default-src 'none'; script-src-elem 'self' https://cdnjs.cloudflare.com https://cloudfront.net *.cloudfront.net; script-src 'self' https://cdnjs.cloudflare.com https://cloudfront.net; connect-src 'self'; img-src 'self' https://gossipsweb.net/images/ https://cloudfront.net *.cloudfront.net; style-src-elem 'self' https://cloudfront.net *.cloudfront.net; style-src 'self' https://cloudfront.net *.cloudfront.net; base-uri 'self'; font-src 'self'; frame-src 'self'; form-action 'self';"
    Permissions-Policy = "accelerometer=(), ambient-light-sensor=(), autoplay=(), battery=(), camera=(), cross-origin-isolated=(), display-capture=(), document-domain=(), encrypted-media=(), execution-while-not-rendered=(), execution-while-out-of-viewport=(), fullscreen=(self), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), navigation-override=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(), usb=(), web-share=(self), xr-spatial-tracking=();"
    Set-Cookie = "SameSite=Strict; Secure"

[build.environment]
  NODE_VERSION = "14"
  NPM_FLAGS = "--prefix=/dev/null"

[build]
  base = "/"
  publish = "dist/"
  command = "pnpm i && pnpm run config && pnpm build || ( npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run config && npx pnpm build)"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

[[redirects]]
  from = "/home"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/index"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/alex"
  to = "/"
  status = 301
  force = true
