[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Content-Security-Policy = "default-src 'none'; script-src 'self' https://cdnjs.cloudflare.com; connect-src 'self'; img-src 'self'; style-src 'self'; base-uri 'self'; font-src 'self'; frame-src 'self'; form-action 'self';"
    # Permissions-Policy= "encrypted-media=(src); accelerometer=(); ambient-light-sensor=(); autoplay=(); camera=(); fullscreen=(self); geolocation=(); gyroscope=(); magnetometer=(); microphone=(); midi=(); payment=(self); picture-in-picture=(); speaker=(); sync-xhr=(); usb=(); vr=();"
    # Feature Policy is to be renamed to Permissions-Policy, however it is widely unsupported in majority of browsers.
    # Browser payment may be used.
    Feature-Policy = "accelerometer 'none'; ambient-light-sensor 'none'; autoplay 'none'; camera 'none'; encrypted-media 'src'; fullscreen 'self'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; payment 'self'; picture-in-picture 'none'; speaker 'none'; sync-xhr 'none'; usb 'none'; vr 'none';"
    Set-Cookie = "SameSite=Strict; Secure"

[build]
  base = "/"
  publish = "dist/"
  command = "pnpm build || ( npm install pnpm && pnpm build )"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

[[redirects]]
  from = "/home"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/index"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/alex"
  to = "/"
  status = 301
  force = true
